-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity adder is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    a_TVALID : IN STD_LOGIC;
    a_TREADY : OUT STD_LOGIC;
    b_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    b_TVALID : IN STD_LOGIC;
    b_TREADY : OUT STD_LOGIC;
    c_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_TVALID : OUT STD_LOGIC;
    c_TREADY : IN STD_LOGIC );
end;


architecture behav of adder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "adder,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.016000,HLS_SYN_LAT=130,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=225,HLS_SYN_LUT=268,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal a_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal a_0_vld_in : STD_LOGIC;
    signal a_0_vld_out : STD_LOGIC;
    signal a_0_ack_in : STD_LOGIC;
    signal a_0_ack_out : STD_LOGIC;
    signal a_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal a_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal a_0_sel_rd : STD_LOGIC := '0';
    signal a_0_sel_wr : STD_LOGIC := '0';
    signal a_0_sel : STD_LOGIC;
    signal a_0_load_A : STD_LOGIC;
    signal a_0_load_B : STD_LOGIC;
    signal a_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal a_0_state_cmp_full : STD_LOGIC;
    signal b_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal b_0_vld_in : STD_LOGIC;
    signal b_0_vld_out : STD_LOGIC;
    signal b_0_ack_in : STD_LOGIC;
    signal b_0_ack_out : STD_LOGIC;
    signal b_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal b_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal b_0_sel_rd : STD_LOGIC := '0';
    signal b_0_sel_wr : STD_LOGIC := '0';
    signal b_0_sel : STD_LOGIC;
    signal b_0_load_A : STD_LOGIC;
    signal b_0_load_B : STD_LOGIC;
    signal b_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal b_0_state_cmp_full : STD_LOGIC;
    signal c_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_vld_in : STD_LOGIC;
    signal c_1_vld_out : STD_LOGIC;
    signal c_1_ack_in : STD_LOGIC;
    signal c_1_ack_out : STD_LOGIC;
    signal c_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_sel_rd : STD_LOGIC := '0';
    signal c_1_sel_wr : STD_LOGIC := '0';
    signal c_1_sel : STD_LOGIC;
    signal c_1_load_A : STD_LOGIC;
    signal c_1_load_B : STD_LOGIC;
    signal c_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal c_1_state_cmp_full : STD_LOGIC;
    signal a_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln10_reg_97 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_TDATA_blk_n : STD_LOGIC;
    signal c_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_0_reg_67 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln10_fu_78_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_84_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_reg_101 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln12_fu_90_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_i_0_phi_fu_71_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    a_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                a_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = a_0_ack_out) and (ap_const_logic_1 = a_0_vld_out))) then 
                                        a_0_sel_rd <= not(a_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    a_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                a_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = a_0_ack_in) and (ap_const_logic_1 = a_0_vld_in))) then 
                                        a_0_sel_wr <= not(a_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    a_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                a_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = a_0_state) and (ap_const_logic_0 = a_0_vld_in)) or ((ap_const_lv2_3 = a_0_state) and (ap_const_logic_0 = a_0_vld_in) and (ap_const_logic_1 = a_0_ack_out)))) then 
                    a_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = a_0_state) and (ap_const_logic_0 = a_0_ack_out)) or ((ap_const_lv2_3 = a_0_state) and (ap_const_logic_0 = a_0_ack_out) and (ap_const_logic_1 = a_0_vld_in)))) then 
                    a_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = a_0_vld_in) and (ap_const_logic_1 = a_0_ack_out))) and not(((ap_const_logic_0 = a_0_ack_out) and (ap_const_logic_1 = a_0_vld_in))) and (ap_const_lv2_3 = a_0_state)) or ((ap_const_lv2_1 = a_0_state) and (ap_const_logic_1 = a_0_ack_out)) or ((ap_const_lv2_2 = a_0_state) and (ap_const_logic_1 = a_0_vld_in)))) then 
                    a_0_state <= ap_const_lv2_3;
                else 
                    a_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    b_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                b_0_sel_rd <= ap_const_logic_0;
            else
                if (((b_0_ack_out = ap_const_logic_1) and (b_0_vld_out = ap_const_logic_1))) then 
                                        b_0_sel_rd <= not(b_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    b_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                b_0_sel_wr <= ap_const_logic_0;
            else
                if (((b_0_vld_in = ap_const_logic_1) and (b_0_ack_in = ap_const_logic_1))) then 
                                        b_0_sel_wr <= not(b_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    b_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                b_0_state <= ap_const_lv2_0;
            else
                if ((((b_0_state = ap_const_lv2_2) and (b_0_vld_in = ap_const_logic_0)) or ((b_0_state = ap_const_lv2_3) and (b_0_vld_in = ap_const_logic_0) and (b_0_ack_out = ap_const_logic_1)))) then 
                    b_0_state <= ap_const_lv2_2;
                elsif ((((b_0_state = ap_const_lv2_1) and (b_0_ack_out = ap_const_logic_0)) or ((b_0_state = ap_const_lv2_3) and (b_0_ack_out = ap_const_logic_0) and (b_0_vld_in = ap_const_logic_1)))) then 
                    b_0_state <= ap_const_lv2_1;
                elsif (((not(((b_0_vld_in = ap_const_logic_0) and (b_0_ack_out = ap_const_logic_1))) and not(((b_0_ack_out = ap_const_logic_0) and (b_0_vld_in = ap_const_logic_1))) and (b_0_state = ap_const_lv2_3)) or ((b_0_state = ap_const_lv2_1) and (b_0_ack_out = ap_const_logic_1)) or ((b_0_state = ap_const_lv2_2) and (b_0_vld_in = ap_const_logic_1)))) then 
                    b_0_state <= ap_const_lv2_3;
                else 
                    b_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    c_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                c_1_sel_rd <= ap_const_logic_0;
            else
                if (((c_1_ack_out = ap_const_logic_1) and (c_1_vld_out = ap_const_logic_1))) then 
                                        c_1_sel_rd <= not(c_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    c_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                c_1_sel_wr <= ap_const_logic_0;
            else
                if (((c_1_ack_in = ap_const_logic_1) and (c_1_vld_in = ap_const_logic_1))) then 
                                        c_1_sel_wr <= not(c_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    c_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                c_1_state <= ap_const_lv2_0;
            else
                if ((((c_1_state = ap_const_lv2_2) and (c_1_vld_in = ap_const_logic_0)) or ((c_1_state = ap_const_lv2_3) and (c_1_vld_in = ap_const_logic_0) and (c_1_ack_out = ap_const_logic_1)))) then 
                    c_1_state <= ap_const_lv2_2;
                elsif ((((c_1_state = ap_const_lv2_1) and (c_TREADY = ap_const_logic_0)) or ((c_1_state = ap_const_lv2_3) and (c_TREADY = ap_const_logic_0) and (c_1_vld_in = ap_const_logic_1)))) then 
                    c_1_state <= ap_const_lv2_1;
                elsif (((not(((c_1_vld_in = ap_const_logic_0) and (c_1_ack_out = ap_const_logic_1))) and not(((c_TREADY = ap_const_logic_0) and (c_1_vld_in = ap_const_logic_1))) and (c_1_state = ap_const_lv2_3)) or ((c_1_state = ap_const_lv2_1) and (c_1_ack_out = ap_const_logic_1)) or ((c_1_state = ap_const_lv2_2) and (c_1_vld_in = ap_const_logic_1)))) then 
                    c_1_state <= ap_const_lv2_3;
                else 
                    c_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_67_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_reg_67 <= i_reg_101;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_67 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = a_0_load_A)) then
                a_0_payload_A <= a_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = a_0_load_B)) then
                a_0_payload_B <= a_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((b_0_load_A = ap_const_logic_1)) then
                b_0_payload_A <= b_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((b_0_load_B = ap_const_logic_1)) then
                b_0_payload_B <= b_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((c_1_load_A = ap_const_logic_1)) then
                c_1_payload_A <= add_ln12_fu_90_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((c_1_load_B = ap_const_logic_1)) then
                c_1_payload_B <= add_ln12_fu_90_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                i_reg_101 <= i_fu_84_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln10_reg_97 <= icmp_ln10_fu_78_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, c_TREADY, c_1_state, ap_enable_reg_pp0_iter0, icmp_ln10_fu_78_p2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln10_fu_78_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((icmp_ln10_fu_78_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((c_1_state = ap_const_lv2_1) or ((c_1_state = ap_const_lv2_3) and (c_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    a_0_ack_in <= a_0_state(1);

    a_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_0_ack_out <= ap_const_logic_1;
        else 
            a_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    a_0_data_out_assign_proc : process(a_0_payload_A, a_0_payload_B, a_0_sel)
    begin
        if ((ap_const_logic_1 = a_0_sel)) then 
            a_0_data_out <= a_0_payload_B;
        else 
            a_0_data_out <= a_0_payload_A;
        end if; 
    end process;

    a_0_load_A <= (not(a_0_sel_wr) and a_0_state_cmp_full);
    a_0_load_B <= (a_0_state_cmp_full and a_0_sel_wr);
    a_0_sel <= a_0_sel_rd;
    a_0_state_cmp_full <= '0' when (a_0_state = ap_const_lv2_1) else '1';
    a_0_vld_in <= a_TVALID;
    a_0_vld_out <= a_0_state(0);

    a_TDATA_blk_n_assign_proc : process(a_0_state, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln10_reg_97)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_TDATA_blk_n <= a_0_state(0);
        else 
            a_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    a_TREADY <= a_0_state(1);
    add_ln12_fu_90_p2 <= std_logic_vector(unsigned(a_0_data_out) + unsigned(b_0_data_out));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_boolean_1 = ap_block_state4_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_boolean_1 = ap_block_state4_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(a_0_vld_out, b_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln10_reg_97 = ap_const_lv1_0) and (b_0_vld_out = ap_const_logic_0)) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_logic_0 = a_0_vld_out))));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(a_0_vld_out, b_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97, ap_block_state3_io)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (b_0_vld_out = ap_const_logic_0)) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_logic_0 = a_0_vld_out))));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(a_0_vld_out, b_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97, ap_block_state3_io)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (b_0_vld_out = ap_const_logic_0)) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_logic_0 = a_0_vld_out))));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(c_1_ack_in, icmp_ln10_reg_97)
    begin
                ap_block_state3_io <= ((icmp_ln10_reg_97 = ap_const_lv1_0) and (c_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage1_iter0_assign_proc : process(a_0_vld_out, b_0_vld_out, icmp_ln10_reg_97)
    begin
                ap_block_state3_pp0_stage1_iter0 <= (((icmp_ln10_reg_97 = ap_const_lv1_0) and (b_0_vld_out = ap_const_logic_0)) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_logic_0 = a_0_vld_out)));
    end process;


    ap_block_state4_io_assign_proc : process(c_1_ack_in, icmp_ln10_reg_97)
    begin
                ap_block_state4_io <= ((icmp_ln10_reg_97 = ap_const_lv1_0) and (c_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_assign_proc : process(c_TREADY, c_1_state)
    begin
                ap_block_state5 <= ((c_1_state = ap_const_lv2_1) or ((c_1_state = ap_const_lv2_3) and (c_TREADY = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln10_fu_78_p2)
    begin
        if ((icmp_ln10_fu_78_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(c_TREADY, c_1_state, ap_CS_fsm_state5)
    begin
        if ((not(((c_1_state = ap_const_lv2_1) or ((c_1_state = ap_const_lv2_3) and (c_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_71_p4_assign_proc : process(icmp_ln10_reg_97, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, i_0_reg_67, i_reg_101)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_i_0_phi_fu_71_p4 <= i_reg_101;
        else 
            ap_phi_mux_i_0_phi_fu_71_p4 <= i_0_reg_67;
        end if; 
    end process;


    ap_ready_assign_proc : process(c_TREADY, c_1_state, ap_CS_fsm_state5)
    begin
        if ((not(((c_1_state = ap_const_lv2_1) or ((c_1_state = ap_const_lv2_3) and (c_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b_0_ack_in <= b_0_state(1);

    b_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            b_0_ack_out <= ap_const_logic_1;
        else 
            b_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    b_0_data_out_assign_proc : process(b_0_payload_A, b_0_payload_B, b_0_sel)
    begin
        if ((b_0_sel = ap_const_logic_1)) then 
            b_0_data_out <= b_0_payload_B;
        else 
            b_0_data_out <= b_0_payload_A;
        end if; 
    end process;

    b_0_load_A <= (not(b_0_sel_wr) and b_0_state_cmp_full);
    b_0_load_B <= (b_0_state_cmp_full and b_0_sel_wr);
    b_0_sel <= b_0_sel_rd;
    b_0_state_cmp_full <= '0' when (b_0_state = ap_const_lv2_1) else '1';
    b_0_vld_in <= b_TVALID;
    b_0_vld_out <= b_0_state(0);

    b_TDATA_blk_n_assign_proc : process(b_0_state, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln10_reg_97)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            b_TDATA_blk_n <= b_0_state(0);
        else 
            b_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    b_TREADY <= b_0_state(1);
    c_1_ack_in <= c_1_state(1);
    c_1_ack_out <= c_TREADY;

    c_1_data_out_assign_proc : process(c_1_payload_A, c_1_payload_B, c_1_sel)
    begin
        if ((c_1_sel = ap_const_logic_1)) then 
            c_1_data_out <= c_1_payload_B;
        else 
            c_1_data_out <= c_1_payload_A;
        end if; 
    end process;

    c_1_load_A <= (not(c_1_sel_wr) and c_1_state_cmp_full);
    c_1_load_B <= (c_1_state_cmp_full and c_1_sel_wr);
    c_1_sel <= c_1_sel_rd;
    c_1_state_cmp_full <= '0' when (c_1_state = ap_const_lv2_1) else '1';

    c_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln10_reg_97, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            c_1_vld_in <= ap_const_logic_1;
        else 
            c_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    c_1_vld_out <= c_1_state(0);
    c_TDATA <= c_1_data_out;

    c_TDATA_blk_n_assign_proc : process(c_1_state, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln10_reg_97, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if ((((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln10_reg_97 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            c_TDATA_blk_n <= c_1_state(1);
        else 
            c_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    c_TVALID <= c_1_state(0);
    i_fu_84_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_0_phi_fu_71_p4) + unsigned(ap_const_lv7_1));
    icmp_ln10_fu_78_p2 <= "1" when (ap_phi_mux_i_0_phi_fu_71_p4 = ap_const_lv7_40) else "0";
end behav;
